# Generated by Django 4.2.4 on 2023-08-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('艺术教研中心', '艺术教研中心'), ('传播学系', '传播学系'), ('数字媒体系', '数字媒体系'), ('设计系', '设计系')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(choices=[('教授', '教授'), ('副教授', '副教授'), ('讲师', '讲师')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModels.department')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModels.identity')),
            ],
        ),
    ]
